name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          A: "1//037EscGt"
          B: "PhmNoCgYIAR"
          C: "AAGAMSNwF-L"
          D: "9IrPXvawv1_"
          E: "jDHC7WftQjR"
          F: "ogM3RdPNxw_"
          G: "MaFlLuA5FPf"
          H: "F38ug4_Nye6"
          I: "Kbyn4hC4uD7"
          J: "7DfU"
        run: |
          T="${A}${B}${C}${D}${E}${F}${G}${H}${I}${J}"
          npx firebase-tools@latest deploy --only hosting --token "$T" --project recetas-749f3 --non-interactive
